/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bikeservicesystem;

import static bikeservicesystem.RentBike.Date;
import java.awt.Color;
import java.io.BufferedWriter;
import java.io.FileWriter;
import java.io.IOException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author NEW
 */
public class FixBike extends javax.swing.JFrame {
     static Double price;
static String fix = "Fix_Bike";

    /**
     * Creates new form FixBike
     */
    public FixBike() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton6 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        BikeType = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        Date = new javax.swing.JFormattedTextField();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(414, 896));
        getContentPane().setLayout(null);

        jButton6.setBackground(new java.awt.Color(255, 255, 255));
        jButton6.setFont(new java.awt.Font("Lucida Grande", 0, 48)); // NOI18N
        jButton6.setForeground(new java.awt.Color(204, 204, 204));
        jButton6.setText("<");
        jButton6.setBorder(null);
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6);
        jButton6.setBounds(0, 0, 80, 90);

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel1.setText("Bike Type");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(31, 125, 65, 17);

        BikeType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Street Bike", "Sport Bike", "Naked Bike", "Cruiser Bike", "Commuter Bike" }));
        getContentPane().add(BikeType);
        BikeType.setBounds(22, 154, 170, 27);

        jLabel2.setText("Date ");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(28, 193, 33, 16);

        jLabel3.setText("What Kinds of Problem ? ");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(28, 269, 170, 16);

        jLabel4.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 18)); // NOI18N
        jLabel4.setText("Bike Repairment");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(109, 26, 141, 22);

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Lucida Sans Typewriter", 0, 18)); // NOI18N
        jButton1.setText("NEXT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(270, 520, 107, 52);

        jButton3.setBackground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Settings");
        jButton3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(290, 730, 120, 71);

        jButton4.setBackground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Home");
        jButton4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(0, 730, 120, 71);

        jButton5.setBackground(new java.awt.Color(255, 255, 255));
        jButton5.setText("Orders");
        jButton5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(120, 730, 170, 71);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tight Brakes", "Air Filter", "Low engine Oil", "Chain Slack ", "Drum Brakes " }));
        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(20, 290, 170, 27);

        Date.setForeground(new java.awt.Color(204, 204, 204));
        Date.setText("dd/MM/yy");
        Date.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                DateFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                DateFocusLost(evt);
            }
        });
        getContentPane().add(Date);
        Date.setBounds(20, 220, 170, 26);

        jLabel5.setIcon(new javax.swing.ImageIcon("/Users/fatima/Desktop/iPhone XR, XS Max, 11 – 13.png")); // NOI18N
        getContentPane().add(jLabel5);
        jLabel5.setBounds(0, 0, 410, 890);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {                                         
            // TODO add your handling code here:
            PaymentFix next = new PaymentFix ();
            next.setVisible(true);
            
            String Date1 = Date.getText();
            Date df = new SimpleDateFormat("dd/MM/yy").parse(Date1);
            
            FixBike fix = new FixBike();
            
            String problem = (String) jComboBox1.getSelectedItem();
            ArrayList<String> jComboBox1 = new ArrayList<String>();
            jComboBox1.add("Tight Brakes");
            jComboBox1.add("Air Filter");
            jComboBox1.add("Low engine Oil");
            jComboBox1.add("Chain Slack");
            jComboBox1.add("Drum Brakes");
            
            //Bike type
            String Bike = (String) BikeType.getSelectedItem();
            ArrayList<String> BikeType = new ArrayList<String>();
            BikeType.add("Street Bike");
            BikeType.add("Sport Bike");
            BikeType.add("Naked Bike");
            BikeType.add("Cruiser Bike");
            BikeType.add("Commuter Bike");
            
            String fixBikefile = "fixBikefile.txt";
            try {
                BufferedWriter fileWriter = new BufferedWriter(new FileWriter(fixBikefile, true));
                
                if (jComboBox1.get(0) == problem) {
                    price = 55.0;
                    fileWriter.write("Fix_Bike , "+"Bike Type: " + Bike + " Problem: " + jComboBox1.get(0) + " Price: " + price + " SAR "+" Date: " + Date1);
                    
                } else if (jComboBox1.get(1) == problem) {
                    price = 65.0;
                    fileWriter.write("Fix_Bike , "+"Bike Type: " + Bike + " Problem: " + jComboBox1.get(1) + " Price: " + price+" SAR "+" Date: " + Date1);
                } else if (jComboBox1.get(2) == problem) {
                    price = 80.0;
                    fileWriter.write("Fix_Bike , "+"Bike Type: " + Bike + " Problem: " + jComboBox1.get(2) + " Price: " + price+" SAR "+" Date: " + Date1);
                } else if (jComboBox1.get(3) == problem) {
                    price = 72.0;
                    fileWriter.write("Fix_Bike , "+"Bike Type: " + Bike + " Problem: " + jComboBox1.get(3) + " Price: " + price+" SAR "+" Date: " + Date1);
                } else if (jComboBox1.get(4) == problem) {
                    price = 90.0;
                    fileWriter.write("Fix_Bike , "+"Bike Type: " + Bike + " Problem: " + jComboBox1.get(4) + " Price: " +price+" SAR "+" Date: " + Date1);
                    
                    
                }
                fileWriter.write(" ");
                
                fileWriter.newLine();
                fileWriter.close();
            } catch (IOException ex) {
                
            }
            
        } catch (ParseException ex) {
            Logger.getLogger(FixBike.class.getName()).log(Level.SEVERE, null, ex);

        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        Settings back = new Settings ();
        back.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        MainInterface back = new MainInterface ();
        back.setVisible(true);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        MainInterface back = new MainInterface ();
        back.setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        ViewOrder back = new ViewOrder ();
        back.setVisible(true);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void DateFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_DateFocusGained
        // TODO add your handling code here:
            if (Date.getText().equals("dd/MM/yy")) {
            Date.setText("");
            Date.setForeground(new Color(0, 0, 0));
        }
    }//GEN-LAST:event_DateFocusGained

    private void DateFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_DateFocusLost
        // TODO add your handling code here:
            if (Date.getText().equals("")) {
            Date.setText("dd/MM/yy");
            Date.setForeground(new Color(0, 0, 0));
        }
    }//GEN-LAST:event_DateFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FixBike.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FixBike.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FixBike.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FixBike.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FixBike().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> BikeType;
    public static javax.swing.JFormattedTextField Date;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
}
