/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bikeservicesystem;

import java.awt.Color;
import bikeservicesystem.Welcome;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
/**
 *
 * @author NEW
 */
public class Register extends javax.swing.JFrame {
    static ArrayList<String> fileList = new ArrayList<>();

    /**
     * Creates new form Register
     */
    public Register() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        Fname = new javax.swing.JTextField();
        Lname = new javax.swing.JTextField();
        emText = new javax.swing.JTextField();
        password = new javax.swing.JPasswordField();
        PhoneNumber = new javax.swing.JTextField();
        Language = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        RegNext = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        addressText = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        Date = new javax.swing.JFormattedTextField();
        Address = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 18)); // NOI18N
        jLabel1.setText("Create an account :");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(30, 90, 169, 22);

        jLabel2.setText("First Name");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(30, 130, 68, 16);

        jLabel3.setText("Last Name");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(180, 130, 66, 16);

        jLabel4.setText("Email");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(30, 190, 34, 16);

        jLabel5.setText("Password");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(30, 240, 59, 16);

        jLabel6.setText("Phone Number");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(30, 310, 92, 16);

        jLabel7.setText("Date of Birth");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(30, 440, 79, 16);

        jLabel8.setText("Language");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(30, 500, 60, 16);

        Fname.setForeground(new java.awt.Color(204, 204, 204));
        Fname.setText("First Name");
        Fname.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                FnameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                FnameFocusLost(evt);
            }
        });
        getContentPane().add(Fname);
        Fname.setBounds(30, 150, 130, 26);

        Lname.setForeground(new java.awt.Color(204, 204, 204));
        Lname.setText("Last Name");
        Lname.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                LnameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                LnameFocusLost(evt);
            }
        });
        getContentPane().add(Lname);
        Lname.setBounds(170, 150, 130, 26);

        emText.setForeground(new java.awt.Color(204, 204, 204));
        emText.setText("someone@example.com");
        emText.addHierarchyListener(new java.awt.event.HierarchyListener() {
            public void hierarchyChanged(java.awt.event.HierarchyEvent evt) {
                emTextHierarchyChanged(evt);
            }
        });
        emText.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                emTextFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                emTextFocusLost(evt);
            }
        });
        getContentPane().add(emText);
        emText.setBounds(30, 210, 240, 26);

        password.setForeground(new java.awt.Color(204, 204, 204));
        password.setText("***************");
        password.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                passwordFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                passwordFocusLost(evt);
            }
        });
        getContentPane().add(password);
        password.setBounds(30, 260, 240, 26);

        PhoneNumber.setForeground(new java.awt.Color(204, 204, 204));
        PhoneNumber.setText("05xxxxxxx");
        PhoneNumber.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                PhoneNumberFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                PhoneNumberFocusLost(evt);
            }
        });
        getContentPane().add(PhoneNumber);
        PhoneNumber.setBounds(30, 330, 240, 26);

        Language.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Engilsh", "Arabic" }));
        getContentPane().add(Language);
        Language.setBounds(30, 520, 180, 27);

        jLabel9.setForeground(new java.awt.Color(255, 0, 0));
        jLabel9.setText("*");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(100, 130, 14, 16);

        jLabel10.setForeground(new java.awt.Color(255, 0, 0));
        jLabel10.setText("*");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(250, 130, 6, 16);

        jLabel11.setForeground(new java.awt.Color(255, 0, 0));
        jLabel11.setText("*");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(70, 190, 6, 16);

        jLabel12.setForeground(new java.awt.Color(255, 0, 0));
        jLabel12.setText("*");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(90, 240, 6, 16);

        jLabel13.setForeground(new java.awt.Color(255, 0, 0));
        jLabel13.setText("*");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(130, 310, 6, 16);

        jLabel14.setForeground(new java.awt.Color(255, 0, 0));
        jLabel14.setText("*");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(110, 440, 6, 16);

        jLabel15.setForeground(new java.awt.Color(255, 0, 0));
        jLabel15.setText("*");
        getContentPane().add(jLabel15);
        jLabel15.setBounds(100, 500, 6, 16);

        jLabel16.setFont(new java.awt.Font("Lucida Grande", 0, 8)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 0, 0));
        jLabel16.setText("Containing at least one number,character,and symbol and More than 8 Character");
        jLabel16.setToolTipText("");
        getContentPane().add(jLabel16);
        jLabel16.setBounds(40, 290, 370, 10);

        RegNext.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        RegNext.setText("Register");
        RegNext.setPreferredSize(new java.awt.Dimension(414, 896));
        RegNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegNextActionPerformed(evt);
            }
        });
        getContentPane().add(RegNext);
        RegNext.setBounds(250, 560, 108, 49);

        jButton1.setFont(new java.awt.Font("Lucida Grande", 0, 48)); // NOI18N
        jButton1.setForeground(new java.awt.Color(204, 204, 204));
        jButton1.setText("<");
        jButton1.setBorder(null);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(10, -10, 80, 90);

        addressText.setForeground(new java.awt.Color(204, 204, 204));
        addressText.setText("Building number , street name ...etc");
        addressText.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                addressTextFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                addressTextFocusLost(evt);
            }
        });
        getContentPane().add(addressText);
        addressText.setBounds(30, 390, 240, 26);

        jLabel17.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jLabel17.setText("Register");
        getContentPane().add(jLabel17);
        jLabel17.setBounds(140, 20, 150, 30);

        Date.setForeground(new java.awt.Color(204, 204, 204));
        Date.setText("dd/MM/yyyy");
        Date.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                DateFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                DateFocusLost(evt);
            }
        });
        getContentPane().add(Date);
        Date.setBounds(30, 460, 240, 26);

        Address.setText("Address");
        getContentPane().add(Address);
        Address.setBounds(30, 370, 51, 16);
        getContentPane().add(jLabel18);
        jLabel18.setBounds(0, 0, 380, 620);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void FnameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_FnameFocusGained
        // TODO add your handling code here:
               if(Fname.getText().equals("First Name"))
        {
            Fname.setText("");
            Fname.setForeground(new Color(0,0,0));
        }
    }//GEN-LAST:event_FnameFocusGained

    private void FnameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_FnameFocusLost
        // TODO add your handling code here:
               if(Fname.getText().equals(""))
        {
            Fname.setText("First Name");
            Fname.setForeground(new Color(0,0,0));
        }
    }//GEN-LAST:event_FnameFocusLost

    private void LnameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_LnameFocusGained
        // TODO add your handling code here:
                if(Lname.getText().equals("Last Name"))
        {
            Lname.setText("");
            Lname.setForeground(new Color(0,0,0));
        }
    }//GEN-LAST:event_LnameFocusGained

    private void LnameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_LnameFocusLost
        // TODO add your handling code here:
                if(Lname.getText().equals(""))
        {
            Lname.setText("Last Name");
            Lname.setForeground(new Color(0,0,0));
        }
    }//GEN-LAST:event_LnameFocusLost

    private void emTextFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_emTextFocusGained
        // TODO add your handling code here:
              if(emText.getText().equals("someone@example.com"))
        {
            emText.setText("");
            emText.setForeground(new Color(0,0,0));
        }
    }//GEN-LAST:event_emTextFocusGained

    private void emTextHierarchyChanged(java.awt.event.HierarchyEvent evt) {//GEN-FIRST:event_emTextHierarchyChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_emTextHierarchyChanged

    private void emTextFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_emTextFocusLost
        // TODO add your handling code here:
              if(emText.getText().equals(""))
        {
            emText.setText("someone@example.com");
            emText.setForeground(new Color(0,0,0));
        }
    }//GEN-LAST:event_emTextFocusLost

    private void passwordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passwordFocusGained
        // TODO add your handling code here:
        if(password.getText().equals("***************"))
        {
            password.setText("");
            password.setForeground(new Color(0,0,0));
        }
    }//GEN-LAST:event_passwordFocusGained

    private void passwordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passwordFocusLost
        // TODO add your handling code here:
        if(password.getText().equals(""))
        {
            password.setText("***************");
            password.setForeground(new Color(0,0,0));
        }
    }//GEN-LAST:event_passwordFocusLost

    private void PhoneNumberFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_PhoneNumberFocusGained
        // TODO add your handling code here:
                          if(PhoneNumber.getText().equals("05xxxxxxx"))
        {
            PhoneNumber.setText("");
            PhoneNumber.setForeground(new Color(0,0,0));
        }
    }//GEN-LAST:event_PhoneNumberFocusGained

    private void PhoneNumberFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_PhoneNumberFocusLost
        // TODO add your handling code here:
                               if(PhoneNumber.getText().equals(""))
        {
            PhoneNumber.setText("05xxxxxxx");
            PhoneNumber.setForeground(new Color(0,0,0));
        }
    }//GEN-LAST:event_PhoneNumberFocusLost

    private void RegNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegNextActionPerformed
        try{                                        
            // TODO add your handling code here:
            String Email = emText.getText();
            String firstName = Fname.getText();
            String lastName = Lname.getText();
            String Password = password.getText();
            String Address = addressText.getText();
            String phoneNum = PhoneNumber.getText();
            String Date1 = Date.getText();
            Date df = new SimpleDateFormat("dd/MM/yyyy").parse(Date1);
            String edPattern = "\\d{2}/\\d{2}/\\d{4}";
        java.util.regex.Pattern w = java.util.regex.Pattern.compile(edPattern);
        java.util.regex.Matcher dates = w.matcher(Date1);
        
            
            /*
            - The password must be at least 8 characters long.
            - The password must contain at least:
            - one alpha character [a-zA-Z]
            - one numeric character [0-9]
            - one character that is not alpha or numeric, such as ! # @ $ % ^ & * ( ) - _ = + [ ] ; : ' " , < . > / ?
            - The password must not contain spaces
            */
            String upperCase = "(.*[A-Z].*)";
            String LowUpperCase = "(.*[a-zA-Z].*)";
            String numbers = "(.*[0-9].*)";
            String specialChars = "(.*[ ! # @ $ % ^ & * ( ) - _ = + [ ] ; : ' \" , < . > / ?].*)";
            String space = "(.*[   ].*)";
            
            String ePattern = "^[a-zA-Z0-9.!#$%&'*+/=?^_`{|}~-]+@((\\[[0-9]{1,3}\\.[0-9]{1,3}\\.[0-9]{1,3}\\.[0-9]{1,3}\\])|(([a-zA-Z\\-0-9]+\\.)+[a-zA-Z]{2,}))$";
            java.util.regex.Pattern p = java.util.regex.Pattern.compile(ePattern);
            java.util.regex.Matcher email = p.matcher(Email);
            
            if (lastName.matches(LowUpperCase) && dates.matches() &&email.matches() && Password.matches(upperCase) && Password.matches(numbers) && Password.matches(specialChars) && !Password.matches(space) && Password.length() > 8 && firstName.matches(LowUpperCase)
                    && Address.matches(LowUpperCase) && Address.matches(numbers) && phoneNum.matches("[0-9]{10}")) {
                
                MainInterface next = new MainInterface ();
                next.setVisible(true);
                
            }
            
            else if(EmailsList().contains(Email)){
                JOptionPane.showMessageDialog(null, "Email Already Exists" );
                emText.setText(null);
                
                
            }else if (Email.isEmpty() && Password.isEmpty() && firstName.isEmpty() && lastName.isEmpty() && Address.isEmpty() && phoneNum.isEmpty()) {
                JOptionPane.showMessageDialog(null, "Invalid Register Detalis !" );
                
            } else  {
                JOptionPane.showMessageDialog(null, "Invalid Register Detalis !" );
                emText.setText(null);
                Fname.setText(null);
                Lname.setText(null);
                password.setText(null);
                addressText.setText(null);
                PhoneNumber.setText(null);
                Date.setText(null);
                
            }
            JTextField emText = new JTextField();
            emText.setText(Email);
            
            JTextField Fname = new JTextField();
            Fname.setText(firstName);
            
            JTextField Lname = new JTextField();
            Lname.setText(lastName);
            
            
            JTextField password = new JTextField();
            password.setText(Password);
            
            
            JTextField addressText = new JTextField();
            addressText.setText(Address);
            
            JTextField PhoneNumber = new JTextField();
            PhoneNumber.setText(phoneNum);
            
            JTextField Date = new JTextField();
            Date.setText(Date1);
            
            String file = "userData.txt";
            try{
                BufferedWriter fileWriter = new BufferedWriter(new FileWriter(file,true));
                
                Fname.write(fileWriter);
                fileWriter.write(" ");
                Lname.write(fileWriter);
                fileWriter.write(" ");
                emText.write(fileWriter);
                fileWriter.write(" ");
                
                password.write(fileWriter);
                fileWriter.write(" ");
                addressText.write(fileWriter);
                fileWriter.write(" ");
                Date.write(fileWriter);
                fileWriter.write(" ");
                PhoneNumber.write(fileWriter);
                fileWriter.newLine();
                
                fileWriter.close();
                
                
                
            } catch (IOException ex) {
                
            }
            
        } catch (ParseException ex) {
            Logger.getLogger(Register.class.getName()).log(Level.SEVERE, null, ex);
           
           }
        
    }//GEN-LAST:event_RegNextActionPerformed
public ArrayList<String> EmailsList (){
        try {
            Scanner read = new Scanner(new File("userData.txt"));
            //  String line;
            while (read.hasNext()) {
                String [] line = read.nextLine().split(" ");
                fileList.add(line[0]); 
                
               
            }
                            read.close();

        } catch (IOException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        }
        return fileList;
    }
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Welcome back = new Welcome ();
        back.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void addressTextFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_addressTextFocusGained
        // TODO add your handling code here:
                if(addressText.getText().equals("Building number , street name ...etc"))
        {
            addressText.setText("");
            addressText.setForeground(new Color(0,0,0));
        }
    }//GEN-LAST:event_addressTextFocusGained

    private void addressTextFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_addressTextFocusLost
        // TODO add your handling code here:
                    if(addressText.getText().equals(""))
        {
            addressText.setText("Building number , street name ...etc");
            addressText.setForeground(new Color(0,0,0));
        }
    }//GEN-LAST:event_addressTextFocusLost

    private void DateFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_DateFocusGained
        // TODO add your handling code here:
               if(Date.getText().equals("dd/MM/yyyy"))
        {
            Date.setText("");
            Date.setForeground(new Color(0,0,0));
        }
    }//GEN-LAST:event_DateFocusGained

    private void DateFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_DateFocusLost
        // TODO add your handling code here:
                 if(Date.getText().equals(""))
        {
            Date.setText("dd/MM/yyyy");
            Date.setForeground(new Color(0,0,0));
        }
    }//GEN-LAST:event_DateFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Register().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Address;
    public static javax.swing.JFormattedTextField Date;
    public static javax.swing.JTextField Fname;
    private javax.swing.JComboBox<String> Language;
    public static javax.swing.JTextField Lname;
    public static javax.swing.JTextField PhoneNumber;
    private javax.swing.JButton RegNext;
    public static javax.swing.JTextField addressText;
    public static javax.swing.JTextField emText;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    public static javax.swing.JPasswordField password;
    // End of variables declaration//GEN-END:variables
}
