/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bikeservicesystem;

import java.awt.Color;
import java.io.BufferedWriter;
import java.io.FileWriter;
import java.io.IOException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author NEW
 */
public class RentBike extends javax.swing.JFrame {
     static Double price;
static String rent = "Rent_Bike";
    /**
     * Creates new form RentBike
     */
    public RentBike() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jSpinner1 = new javax.swing.JSpinner();
        jComboBox2 = new javax.swing.JComboBox<>();
        Date = new javax.swing.JFormattedTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(414, 896));
        getContentPane().setLayout(null);

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Lucida Sans Typewriter", 0, 18)); // NOI18N
        jButton1.setText("NEXT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(270, 520, 107, 52);

        jLabel1.setText("Bike Type");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(60, 180, 60, 16);

        jLabel2.setText("Qty");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(60, 230, 22, 16);

        jLabel3.setText("Rental Hours");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(60, 280, 81, 16);

        jLabel4.setText("Date");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(60, 330, 29, 16);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Street Bike", "Sport Bike", "Naked Bike", "Cruiser Bike", "Commuter Bike" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(50, 200, 128, 27);
        getContentPane().add(jSpinner1);
        jSpinner1.setBounds(60, 250, 43, 26);

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2 hours", "3 hours", "4 hours", "5 hours", "6 hours", "7 hours", "8 hours", "9 hours", "10 hours", "11 hours", "12 hours" }));
        getContentPane().add(jComboBox2);
        jComboBox2.setBounds(50, 300, 128, 27);

        Date.setForeground(new java.awt.Color(204, 204, 204));
        Date.setText("dd/MM/yy");
        Date.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                DateFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                DateFocusLost(evt);
            }
        });
        Date.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DateActionPerformed(evt);
            }
        });
        getContentPane().add(Date);
        Date.setBounds(50, 350, 176, 26);

        jButton2.setFont(new java.awt.Font("Lucida Grande", 0, 48)); // NOI18N
        jButton2.setForeground(new java.awt.Color(204, 204, 204));
        jButton2.setText("<");
        jButton2.setBorder(null);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(0, 0, 80, 90);

        jButton3.setBackground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Settings");
        jButton3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(290, 730, 120, 71);

        jButton5.setBackground(new java.awt.Color(255, 255, 255));
        jButton5.setText("Orders");
        jButton5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(120, 730, 170, 71);

        jButton4.setBackground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Home");
        jButton4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(0, 730, 120, 71);

        jLabel5.setIcon(new javax.swing.ImageIcon("/Users/fatima/Desktop/iPhone XR, XS Max, 11 – 13.png")); // NOI18N
        jLabel5.setText("jLabel5");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(0, 0, 410, 900);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void DateFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_DateFocusGained
        // TODO add your handling code here:
          if (Date.getText().equals("dd/MM/yy")) {
            Date.setText("");
            Date.setForeground(new Color(0, 0, 0));
        }
    }//GEN-LAST:event_DateFocusGained

    private void DateFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_DateFocusLost
        // TODO add your handling code here:
          if (Date.getText().equals("")) {
            Date.setText("dd/MM/yy");
            Date.setForeground(new Color(0, 0, 0));
        }
    }//GEN-LAST:event_DateFocusLost

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
            try {                                         
                // TODO add your handling code here:
                

                // Date
                String Date1 = Date.getText();
                Date df = new SimpleDateFormat("dd/MM/yy").parse(Date1);
                
                
                // Bike Type
                String Bike = (String) jComboBox1.getSelectedItem();
                ArrayList<String> jComboBox1 = new ArrayList<String>();
                jComboBox1.add("Street Bike");
                jComboBox1.add("Sport Bike");
                jComboBox1.add("Naked Bike");
                jComboBox1.add("Cruiser Bike");
                jComboBox1.add("Commuter Bike");
                
                //Qty
                int qty = (int) jSpinner1.getValue();
                jSpinner1.setValue(qty);
                
                //Hours
                String rent = (String) jComboBox2.getSelectedItem();
                ArrayList<String> jComboBox2 = new ArrayList<String>();
                jComboBox2.add("-");
                jComboBox2.add("-");
                jComboBox2.add("2 hours");
                jComboBox2.add("3 hours");
                jComboBox2.add("4 hours");
                jComboBox2.add("5 hours");
                jComboBox2.add("6 hours");
                jComboBox2.add("7 hours");
                jComboBox2.add("8 hours");
                jComboBox2.add("9 hours");
                jComboBox2.add("10 hours");
                jComboBox2.add("11 hours");
                jComboBox2.add("12 hours");
                jComboBox2.add("24 hours");
                
                //
                String fileRent = "RentInfo.txt";
                try {
                    BufferedWriter fileWriter = new BufferedWriter(new FileWriter(fileRent, true));
                    
                    for (int i = 0; jComboBox2.size() > i; i++)
                        
                        if (jComboBox1.get(0) == Bike && jComboBox2.get(i).equals(rent)) {
                            price = 35.0*qty*i;
                            fileWriter.write("Book_Bike " +"Bike = " + jComboBox1.get(0) + " Price : " + price + " SAR " + " , Qty : " + qty + " , Rental Hours : " + rent + " , Date&Time : " + Date1);
                            
                            //Show payment interface
                            Payment next = new Payment ();
                            next.setVisible(true);
                            
                        } else if (jComboBox1.get(1) == Bike && jComboBox2.get(i).equals(rent)) {
                            price = 30.0*qty*i;
                            fileWriter.write("Book_Bike " +"Bike = " + jComboBox1.get(1) + " Price : " + price + " SAR " + " , Qty : " + qty + " , Rental Hours : " + rent + " , Date&Time : " + Date1);
                            //Show payment interface
                            Payment next = new Payment ();
                            next.setVisible(true);
                        } else if (jComboBox1.get(2) == Bike && jComboBox2.get(i).equals(rent)) {
                            price = 25.0*qty*i;
                            fileWriter.write("Book_Bike " + "Bike = " + jComboBox1.get(2) + " Price : " + price + " SAR " + " , Qty : " + qty + " , Rental Hours : " + rent + " , Date&Time : " + Date1);
                            //Show payment interface
                            Payment next = new Payment ();
                            next.setVisible(true);
                        } else if (jComboBox1.get(3) == Bike && jComboBox2.get(i).equals(rent)) {
                            price = 20.0*qty*i;
                            fileWriter.write("Book_Bike " + "Bike = " + jComboBox1.get(3) + " Price : " + price + " SAR " + " , Qty : " + qty + " , Rental Hours : " + rent + " , Date&Time : " + Date1);
                            //Show payment interface
                            Payment next = new Payment ();
                            next.setVisible(true);
                        } else if (jComboBox1.get(4) == Bike && jComboBox2.get(i).equals(rent) ) {
                            price = 20.0*qty*i;
                            fileWriter.write("Book_Bike " + "Bike = " + jComboBox1.get(4) + " Price : " + price + " SAR " + " , Qty : " + qty + " , Rental Hours : " + rent + " , Date&Time : " + Date1);
                            Payment next = new Payment ();
                            next.setVisible(true);
                        }
                    fileWriter.newLine();
                    fileWriter.close();
                } catch (IOException ex) {
                }
            } catch (ParseException ex) {
            }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        Welcome back = new Welcome ();
        back.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        Settings back = new Settings ();
        back.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        ViewOrder back = new ViewOrder ();
        back.setVisible(true);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        MainInterface back = new MainInterface ();
        back.setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void DateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RentBike.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RentBike.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RentBike.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RentBike.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RentBike().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JFormattedTextField Date;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JSpinner jSpinner1;
    // End of variables declaration//GEN-END:variables
}
